### ISSUE TITLE
infografia

### ISSUE THREAD

**Issue by ArturoAngonJose** [SistemasTecTlaxiaco/infografia-de-hilos-ArturoAngonJose#2]
[infografia_HILOS.pdf](https://github.com/SistemasTecTlaxiaco/infografia-de-hilos-ArturoAngonJose/files/6459833/infografia_HILOS.pdf)

**Comment by Band-hi** [comment]
Calificación: 18/20

Calificó: Gandhi Salazar

**Comment by josealfredo79** [comment]
Bien hecho y revisado
